CREATE TABLE Books (
    BookID INT PRIMARY KEY AUTO_INCREMENT,
    Image BLOB,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    Rating INT,
    Price DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL DEFAULT 0
);

INSERT INTO Books (Title, Author, Genre, Rating, Price, StockQuantity) VALUES 
('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 'Fantasy', 4, 21.00, 45),
('Moby-Dick', 'Herman Melville', 'Classic', 3, 26.00, 40),
('Brave New World', 'Aldous Huxley', 'Dystopian', 4, 19.00, 50),
('The Odyssey', 'Homer', 'Epic', 5, 20.00, 35),
('Frankenstein', 'Mary Shelley', 'Gothic', 4, 18.00, 30),
('Wuthering Heights', 'Emily Bronte', 'Gothic', 5, 23.00, 25),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Gothic', 4, 24.00, 20),
('Don Quixote', 'Miguel de Cervantes', 'Classic', 5, 22.00, 55),
('The Count of Monte Cristo', 'Alexandre Dumas', 'Adventure', 5, 28.00, 50),
('Dracula', 'Bram Stoker', 'Gothic', 4, 17.00, 40),
('The Iliad', 'Homer', 'Epic', 5, 19.00, 45),
('Les Misérables', 'Victor Hugo', 'Classic', 5, 27.00, 60),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Psychological Fiction', 4, 25.00, 35),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 5, 30.00, 30),
('War and Peace', 'Leo Tolstoy', 'Historical Fiction', 4, 29.00, 55),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical Fiction', 5, 26.00, 50),
('Anna Karenina', 'Leo Tolstoy', 'Classic', 5, 28.00, 40),
('Jane Eyre', 'Charlotte Bronte', 'Gothic', 4, 23.00, 35),
('The Odyssey', 'Homer', 'Epic', 5, 20.00, 45),
('The Divine Comedy', 'Dante Alighieri', 'Epic', 5, 24.00, 30),
('The Catcher in the Rye', 'J.D. Salinger', 'Literary Fiction', 4, 20.00, 50),
('To Kill a Mockingbird', 'Harper Lee', 'Classic', 3, 25.00, 30),
('Pride and Prejudice', 'Jane Austen', 'Romance', 5, 15.00, 40),
('1984', 'George Orwell', 'Dystopian', 4, 18.00, 60),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Literary Fiction', 5, 22.00, 55),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 4, 30.00, 20),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 3, 28.00, 25),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 5, 19.00, 45),
('Animal Farm', 'George Orwell', 'Allegory', 4, 17.00, 35),
('The Da Vinci Code', 'Dan Brown', 'Mystery', 4, 21.00, 50),
('The Catcher in the Rye', 'J.D. Salinger', 'Literary Fiction', 4, 20.00, 50),
('To Kill a Mockingbird', 'Harper Lee', 'Classic', 3, 25.00, 30),
('Pride and Prejudice', 'Jane Austen', 'Romance', 5, 15.00, 40),
('1984', 'George Orwell', 'Dystopian', 4, 18.00, 60),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Literary Fiction', 5, 22.00, 55),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 4, 30.00, 20),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 3, 28.00, 25),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 5, 19.00, 45),
('Animal Farm', 'George Orwell', 'Allegory', 4, 17.00, 35),
('The Da Vinci Code', 'Dan Brown', 'Mystery', 4, 21.00, 50);
